In [14]:
## import the necessary libraries

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
## User defined dataset (Two simple documents containing one sentence each)

documentA = 'the man went out for a walk'
documentB = 'the children sat around the fire'

# BOW (to convert text into vectors of numbers)

In [3]:
# splits two documents in individual words

bagOfWordsA = documentA.split(' ')
bagOfWordsB = documentB.split(' ')

print(bagOfWordsA)
print(bagOfWordsB)

['the', 'man', 'went', 'out', 'for', 'a', 'walk']
['the', 'children', 'sat', 'around', 'the', 'fire']


In [4]:
# remove any duplicate words

uniqueWords = set(bagOfWordsA).union(set(bagOfWordsB))

In [5]:
print(uniqueWords)

{'for', 'a', 'around', 'the', 'walk', 'sat', 'went', 'out', 'man', 'fire', 'children'}


In [9]:
# create a dictionary of words and their occurence for each document in the corpus (collection of documents)

numOfWordsA = dict.fromkeys(uniqueWords, 0)

for word in bagOfWordsA:
    numOfWordsA[word] += 1
        
numOfWordsB = dict.fromkeys(uniqueWords, 0)

for word in bagOfWordsB:
    numOfWordsB[word] += 1
    
df = pd.DataFrame([numOfWordsA, numOfWordsB])

print(df)

   for  a  around  the  walk  sat  went  out  man  fire  children
0    1  1       0    1     1    0     1    1    1     0         0
1    0  0       1    2     0    1     0    0    0     1         1


In [16]:
#Term Frequency (TF)


def computeTF(wordDict, bagOfWords):
    tfDict = {}
    bagOfWordsCount = len(bagOfWords)
    for word, count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
    return tfDict

In [20]:
# compute the term frequency for each of documents

tfA = computeTF(numOfWordsA, bagOfWordsA)
tfB = computeTF(numOfWordsB, bagOfWordsB)
print(tfA)
print(tfB)

{'for': 0.14285714285714285, 'a': 0.14285714285714285, 'around': 0.0, 'the': 0.14285714285714285, 'walk': 0.14285714285714285, 'sat': 0.0, 'went': 0.14285714285714285, 'out': 0.14285714285714285, 'man': 0.14285714285714285, 'fire': 0.0, 'children': 0.0}
{'for': 0.0, 'a': 0.0, 'around': 0.16666666666666666, 'the': 0.3333333333333333, 'walk': 0.0, 'sat': 0.16666666666666666, 'went': 0.0, 'out': 0.0, 'man': 0.0, 'fire': 0.16666666666666666, 'children': 0.16666666666666666}


In [27]:
# Inverse Data Frequency (IDF)

def computeIDF(documents):
    import math
    N = len(documents)
    
    idfDict = dict.fromkeys(documents[0].keys(), 0)

    for document in documents:
        for word, val in document.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log(N / float(val))
    return idfDict

In [28]:
# The IDF is computed once for all documents

idfs = computeIDF([numOfWordsA, numOfWordsB])
df = pd.DataFrame([idfs])

print(df)

        for         a    around  the      walk       sat      went       out  \
0  0.693147  0.693147  0.693147  0.0  0.693147  0.693147  0.693147  0.693147   

        man      fire  children  
0  0.693147  0.693147  0.693147  


In [29]:
# The TF-IDF is simply the TF multiplied by IDF

def computeTFIDF(tfBagOfWords, idfs):
    tfidf = {}
    for word, val in tfBagOfWords.items():
        tfidf[word] = val * idfs[word]
    return tfidf

In [30]:
# compute the TF-IDF scores for all the words in the corpus

tfidfA = computeTFIDF(tfA, idfs)
tfidfB = computeTFIDF(tfB, idfs)
df = pd.DataFrame([tfidfA, tfidfB])

print(df)

        for         a    around  the      walk       sat      went       out  \
0  0.099021  0.099021  0.000000  0.0  0.099021  0.000000  0.099021  0.099021   
1  0.000000  0.000000  0.115525  0.0  0.000000  0.115525  0.000000  0.000000   

        man      fire  children  
0  0.099021  0.000000  0.000000  
1  0.000000  0.115525  0.115525  


# Example 2

In [28]:
import nltk
import re
import numpy as np
  
# execute the text here as :
text = """Beans. I was trying to explain to somebody as we were flying in,that’s corn. That’s beans. And they were very impressed at my agricultural knowledge. Please give it up for Amaury once again for that outstanding introduction. I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we’re lucky to have him, your Senator, Dick Durbin is here. I also noticed, by the way, former Governor Edgar here, who I haven’t seen in a long time, and somehow he has not aged and I have. And it’s great to see you, Governor. I want to thank President Killeen and everybody at the U of I System for making it possible for me to be here today. And I am deeply honored at the Paul Douglas Award that is being given to me. He is somebody who set the path for so much outstanding public service here in Illinois. Now, I want to start by addressing the elephant in the room. I know people are still wondering why I didn’t speak at the commencement.  """
dataset = nltk.sent_tokenize(text)
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W', ' ', dataset[i])
    dataset[i] = re.sub(r'\s+', ' ', dataset[i])

In [29]:
print(dataset)

['beans ', 'i was trying to explain to somebody as we were flying in that s corn ', 'that s beans ', 'and they were very impressed at my agricultural knowledge ', 'please give it up for amaury once again for that outstanding introduction ', 'i have a bunch of good friends here today including somebody who i served with who is one of the finest senators in the country and we re lucky to have him your senator dick durbin is here ', 'i also noticed by the way former governor edgar here who i haven t seen in a long time and somehow he has not aged and i have ', 'and it s great to see you governor ', 'i want to thank president killeen and everybody at the u of i system for making it possible for me to be here today ', 'and i am deeply honored at the paul douglas award that is being given to me ', 'he is somebody who set the path for so much outstanding public service here in illinois ', 'now i want to start by addressing the elephant in the room ', 'i know people are still wondering why i d

Step 2: Obtaining most frequent words in our text.

We will apply the following steps to generate our model.

1)We declare a dictionary to hold our bag of words.
2)Next we tokenize each sentence to words.
3)Now for each word in sentence, we check if the word exists in our dictionary.
If it does, then we increment its count by 1. If it doesn’t, we add it to our dictionary and set its count as 1.

In [3]:
# Creating the Bag of Words model
word2count = {}
for data in dataset:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

In [11]:
print(word2count)

{'beans': 2, 'i': 12, 'was': 1, 'trying': 1, 'to': 8, 'explain': 1, 'somebody': 3, 'as': 1, 'we': 2, 'were': 2, 'flying': 1, 'in': 5, 'that': 4, 's': 3, 'corn': 1, 'and': 7, 'they': 1, 'very': 1, 'impressed': 1, 'at': 4, 'my': 1, 'agricultural': 1, 'knowledge': 1, 'please': 1, 'give': 1, 'it': 3, 'up': 1, 'for': 5, 'amaury': 1, 'once': 1, 'again': 1, 'outstanding': 2, 'introduction': 1, 'have': 3, 'a': 2, 'bunch': 1, 'of': 3, 'good': 1, 'friends': 1, 'here': 5, 'today': 2, 'including': 1, 'who': 4, 'served': 1, 'with': 1, 'is': 4, 'one': 1, 'the': 9, 'finest': 1, 'senators': 1, 'country': 1, 're': 1, 'lucky': 1, 'him': 1, 'your': 1, 'senator': 1, 'dick': 1, 'durbin': 1, 'also': 1, 'noticed': 1, 'by': 2, 'way': 1, 'former': 1, 'governor': 2, 'edgar': 1, 'haven': 1, 't': 2, 'seen': 1, 'long': 1, 'time': 1, 'somehow': 1, 'he': 2, 'has': 1, 'not': 1, 'aged': 1, 'great': 1, 'see': 1, 'you': 1, 'want': 2, 'thank': 1, 'president': 1, 'killeen': 1, 'everybody': 1, 'u': 1, 'system': 1, 'making'

when processing large texts, the number of words could reach millions. We do not need to use all those words. Hence, we select a particular number of most frequently used words. To implement this we use:

In [4]:
import heapq
freq_words = heapq.nlargest(100, word2count, key=word2count.get)

Step: Building the Bag of Words model
In this step we construct a vector, which would tell us whether a word in each sentence is a frequent word or not. If a word in a sentence is a frequent word, we set it as 1, else we set it as 0.

In [24]:
X = []
numOfWordsA={}
for data in dataset:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
            numOfWordsA[word] = 1
        else:
            vector.append(0)
            numOfWordsA[word] = 0
    X.append(vector)
X = np.asarray(X)
df= pd.DataFrame([numOfWordsA])

In [6]:
print(X)

[[0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]]


In [25]:
print(df)

   i  the  to  and  in  for  here  that  at  who  ...  deeply  honored  paul  \
0  1    1   0    0   0    0     0     0   1    0  ...       0        0     0   

   douglas  award  being  given  set  path  so  
0        0      0      0      0    0     0   0  

[1 rows x 100 columns]
