In [1]:
#import all necessary libraries
import sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.datasets import load_breast_cancer 
from sklearn.svm import SVC 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split 
 
#load the dataset and split it into training and testing sets
dataset = load_breast_cancer()
X=dataset.data
Y=dataset.target
X_train, X_test, y_train, y_test = train_test_split( 
                        X,Y,test_size = 0.30, random_state = 101) 
# train the model on train set without using GridSearchCV 
model = SVC() 
model.fit(X_train, y_train) 
   
# print prediction results 
predictions = model.predict(X_test) 
print(classification_report(y_test, predictions)) 

              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171



In [2]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions)) 

[[ 56  10]
 [  3 102]]


In [3]:
import numpy as np
print(X_test.shape)
print(Y.shape)

(171, 30)
(569,)


class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)

In [4]:
# defining parameter range 
param_grid = {'C': [0.1,1,10, 100],  
              #'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'gamma':['scale', 'auto'],
              'kernel': ['linear']}  
   
grid = GridSearchCV(SVC(), param_grid, refit = True,cv =5, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 
# print best parameter after tuning 
print(grid.best_params_) 
grid_predictions = grid.predict(X_test) 
   
# print classification report 
print(classification_report(y_test, grid_predictions)) 

Fitting 5 folds for each of 8 candidates, totalling 40 fits
{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        66
           1       0.94      0.98      0.96       105

    accuracy                           0.95       171
   macro avg       0.96      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [10]:
print(confusion_matrix(y_test,grid_predictions)) 

[[ 60   6]
 [  2 103]]


##  u can also use

from sklearn.utils.fixes import loguniform
{'C': loguniform(1e0, 1e3),
 'gamma': loguniform(1e-4, 1e-3),
 'kernel': ['rbf'],
 'class_weight':['balanced', None]}


In [13]:
from sklearn.model_selection import RandomizedSearchCV
import scipy
random_grid = {'C': scipy.stats.expon(scale=100), 'gamma': scipy.stats.expon(scale=.1),
  'kernel': ['linear'], 'class_weight':['balanced', None]}
rf_random = RandomizedSearchCV(SVC(), param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)# Fit the random search model

In [14]:
# fitting the model for grid search 
rf_random.fit(X_train, y_train) 
 
# print best parameter after tuning 
print(rf_random.best_params_) 
rf_random_predictions = rf_random.predict(X_test) 
   
# print classification report 
print(classification_report(y_test, rf_random_predictions)) 

Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'C': 93.533302064961, 'class_weight': 'balanced', 'gamma': 0.05987451438464722, 'kernel': 'linear'}
              precision    recall  f1-score   support

           0       0.98      0.89      0.94        66
           1       0.94      0.99      0.96       105

    accuracy                           0.95       171
   macro avg       0.96      0.94      0.95       171
weighted avg       0.95      0.95      0.95       171



In [15]:
print(confusion_matrix(y_test, rf_random_predictions)) 

[[ 59   7]
 [  1 104]]
